version: "3.3"
services:
  python-matter-server:
    container_name: matter-server
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - /srv/matter/server:/data
    network_mode: host
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - "docker-volume-backup.stop-during-backup=true"  
networks: {}
