version: "3.8"
services:
  glances:
    image: nicolargo/glances
    container_name: glances
    restart: always
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /srv/glances/config:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/sda1:/dsks/sda1
      - /dev/sdb1:/dsks/sdb1
      - /mnt/huge:/mnt/huge:ro
      - /mnt/media:/mnt/media:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - TZ=Europe/London
      - GLANCES_OPT=-w
    ports:
      - 61208-61209:61208-61209
networks: {}
