version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - type: bind
        source: /mnt/media/Movies
        target: /media/Movies
      - type: bind
        source: /mnt/media/Music
        target: /media/Music
      - type: bind
        source: /mnt/media/TV Shows
        target: /media/TV Shows
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.example.com
    networks:
      - proxy
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - "docker-volume-backup.stop-during-backup=true"  
networks:
  proxy:
    external: true
