version: "3.8"
services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    #    ports:
    #      - 192.168.1.101:8090:8090
    volumes:
      - /srv/beszel/data:/beszel_data
    networks:
      - proxy
    labels:
      # Adding this label means this container should be stopped while it's being backed up:
      - "docker-volume-backup.stop-during-backup=true"  
networks:
  proxy:
    external: true
  beszel:
    name: beszel
    ipam:
      config:
        - subnet: 172.24.3.0/24
